### ISSUE TITLE
sm-operator chart not listed in the index

### ISSUE THREAD

**Issue by AaronSeibert** [bitwarden/helm-charts#154]
### Steps To Reproduce

From https://bitwarden.com/help/secrets-manager-kubernetes-operator/#example-usage-chart follow the directions for adding the repositor to helm - specifically `helm show values bitwarden/sm-operator > my-values.yaml`

### Expected Result

When generating the sample values file, a file should be generated

### Actual Result

❯ helm show values bitwarden/sm-operator > my-values.yaml
Error: chart "sm-operator" matching  not found in bitwarden index. (try 'helm repo update'): no chart version found for sm-operat

### Chart Version

N/A

### Environment Details

N/A - chart doesn't actually exist

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by AaronSeibert** [comment]
Showing update and then search repo output:

```
❯ helm repo update bitwarden
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitwarden" chart repository
Update Complete. ⎈Happy Helming!⎈
❯ helm search repo bitwarden
NAME               CHART VERSIONAPP VERSIONDESCRIPTION                                       
bitwarden/self-host2024.6.0     2024.6.1   A Helm chart for deploying a Bitwarden instance
```

**Comment by AaronSeibert** [comment]
Looks like a `--devel` flag is required currently due to the Beta status. Not sure if you want to keep this open to notate in documentation?

**Comment by thekoma** [comment]
There is already an annotation in the documentation AFAIK. Also if you want to point at this helm via flux helmrelease (fluxcd.io) you need to specify the semver:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sm-operator
  namespace: flux-system
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: sm-operator
      version: ">=0.1.0-Beta"
      sourceRef:
        kind: HelmRepository
        name: bitwarden
        namespace: flux-system
  interval: 2m30s
  values:
    settings:
      # How often the secrets synchronize in seconds.  Minimum value is 180.
      bwSecretsManagerRefreshInterval: 300
```
