### ISSUE TITLE
Helm install fail with database statefulset

### ISSUE THREAD

**Issue by sebglon** [bitwarden/helm-charts#66]
### Steps To Reproduce

run this cmd:
```
helm install bitwarden bitwarden/self-host --version=0.1.7-Beta  --namespace bitwarden --values values.yaml
```
with this minimal values: 
```
database:
  enabled: true
  volume:
    backups:
      size: 20Gi
    data:
      size: 20Gi
    log:
      size: 10Gi
general:
  admins: false
  domain: test.env.fr
  email:
    replyToEmail: service@env.fr
    smtpHost: xxxxx
    smtpPort: "587"
  ingress:
    annotations:
    enabled: true
secrets:
  secretName: custom
```

### Expected Result

Helm release is deployed

### Actual Result

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec
```

### Chart Version

0.1.7-Beta

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.
